name: Kurios7
favicon: null
layout_spectrum: 0.14148133620619774
typography_spectrum: 0.11192490835674107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18a4b3'
    - '#fb1263'
    - '#f3c4bc'
    - '#90aeb9'
    - '#b853b3'
  brandStrength: 0.014541840413585305
  lightness: 0.21631775819696486
  saturation: 0.04795278236269951
  rhythmicContrast: 0.47389009105972946
purpose: []
